### PR TITLE
Added asynchronous dismissal of actions

### PR DESCRIPTION
**Pull request by Haud**
@MichaelCampbell @htinlinn

### CODE REVIEW

**Comment by MichaelCampbell** [comment]
:+1:

**Comment by htinlinn** [comment]
this looks good but was there any reason we have `viewController` as a property in `YoshiActionResult` instead of having it as an associated value in `YoshiResult`?

**Comment by Haud** [comment]
@htinlinn at this point, no. I can just refactor out `YoshiActionResult` and just have the function return `YoshiResult`. Would you guys want me to do that here or in a subsequent PR? This would be a breaking change.

**Comment by MichaelCampbell** [comment]
I vote subsequent PR, @htinlinn?

**Comment by MichaelCampbell** [comment]
@Haud Conflicts

**Comment by MichaelCampbell** [comment]
still a :+1: for me

**Comment by htinlinn** [comment]
alright. it makes sense to do this in a subsequent pr.

**Comment by htinlinn** [comment]
:+1:

**Pull request merged**
