### PR TITLE
Refactored UIWindow use to accomodate iPad Presentation as formsheet

### PR DESCRIPTION
**Pull request by MichaelCampbell**
@Haud @htinlinn 
Just updating the way we present the `DebugViewController`, as it looks pretty bad on iPad

### CODE REVIEW

**Comment by Haud** [comment]
What's this doing?

**Comment by MichaelCampbell** [comment]
It gets the rootViewController from the Window then presents the `DebugViewController` modally in a formsheet

**Comment by Haud** [comment]
I see we're getting rid of the window and making this a modal presentation. My worry is that because the invocations are global that it's possible to present this view controller without even seeing it.

**Comment by MichaelCampbell** [comment]
Can you think of a case where that would happen? This presents on top of the visible view controller

**Comment by Haud** [comment]
If another window is being presented. I dunno, I guess an edge case but something that I think about. Maybe we should document the behavior in the README so that this is documented -- or better, update the APIs to allow the user to specify a presenting window if they want to use something other than the AppDelegate's window.

**Comment by htinlinn** [comment]
We will at least need to get the top most view controller I think, not just root view controller. This doesn't work if you already have an alert controller presented in your root view controller.

**Comment by MichaelCampbell** [comment]
Just added logic to present on top of the rootViewController's presentedViewController

**Comment by Haud** [comment]
I still think we should have a `presentingWindow: UIWindow?` property for the user to specify where they want the menu to appear, in the event that the AppDelegate.window is not the presenting window.

**Comment by MichaelCampbell** [comment]
Closing in favor of #23

**Pull request closed without merging**
